---
title: "03_tables"
output: html_document
---

# Environment
```{r}
library(tableone)
library(kableExtra)
library(knitr)
library(janitor)
```

#Table one 1º
```{r}
#Lista de variables incluidas en la table 1
vars_in_table1 <- names(final_df_er_sepsis %>% select( sex,age,ethnicity,er_los_hrs,unitdischargestatus,apachescoreIV,bact_resist_level, final_charlson_score, hist_metastasis_bin,hist_vih_sida_bin,hist_cirrosis_liver_bin,hist_stroke_bin,hist_renal_bin,hist_diabetes_bin,hist_cancer_bin,hist_leukemia_bin,hist_lymphoma_bin,hist_myocardial_infar_bin,hist_chf_bin,hist_pvd_bin,hist_tia_bin,hist_dementia_bin,hist_copd_bin,hist_ctd_bin,hist_pud_bin,hist_liver_bin,unit_cardiac_icu,unit_ccu_cticu,unit_csicu,unit_cticu,unit_med_surg_icu,unit_micu,unit_neuro_icu,unit_sicu,apacheadmissiondx_abscess_neurologic,apacheadmissiondx_abscess_cranial_surgery,apacheadmissiondx_ards_non_cardiogenic_pulmonary,apacheadmissiondx_arthritis_septic,apacheadmissiondx_cellulitis_and_localized_infections,apacheadmissiondx_cellulitis_and_localized_infections_surgeryfor,apacheadmissiondx_cholecystectomy_cholanfitis,apacheadmissiondx_complications_previas_gi_surgery,apacheadmissiondx_complications_previous_open_heart_general,apacheadmissiondx_complications_previous_open_heart_specific,apacheadmissiondx_diverticular_disease_surgeryfor,apacheadmissiondx_endocarditis,apacheadmissiondx_fistula_surgery,apacheadmissiondx_gi_abscess_cyst,apacheadmissiondx_gi_abscess_cyst_primary,apacheadmissiondx_gi_obstuction,apacheadmissiondx_gi_perforation_rupture,apacheadmissiondx_gi_perforation_rupture_surgery,apacheadmissiondx_infection_other_surgery,
apacheadmissiondx_inflammatory_bowel_disease_surgery,apacheadmissiondx_meningitis,apacheadmissiondx_pancreatitis_surgery,apacheadmissiondx_peritonitis,apacheadmissiondx_peritonitis_surgery,apacheadmissiondx_pneumonia_aspiration,apacheadmissiondx_pneumonia_bacterial,apacheadmissiondx_pneumonia_fungal,apacheadmissiondx_pneumonia_other,apacheadmissiondx_pneumonia_parasitic,apacheadmissiondx_pneumonia_viral,apacheadmissiondx_renal_infection,apacheadmissiondx_sepsi_Cutaneous,apacheadmissiondx_sepsis_gi,apacheadmissiondx_sepsis_gynecologic,apacheadmissiondx_sepsis_other,apacheadmissiondx_sepsis_pulmonary,apacheadmissiondx_sepsis_renal_uti,apacheadmissiondx_sepsis_unknown,apacheadmisiondx_thoracotomy_for_thoracic_infection))
```

#Crea un conjunto de datos con solo variables seleccionadas utilizando nuestro conjunto de datos original y genera una lista vacía para almacenar variables categóricas
```{r}
table1_dataset <- final_df_order[,vars_in_table1]
cat_variables <- rep(NA, length(vars_in_table1))
stratifyby <- "unitdischargestatus"

```

#Detects whether a variable is categorical or not
```{r}
cont <- 1
for (i in 1:length(vars_in_table1)) {
  if ( n_distinct(table1_dataset[vars_in_table1[i]]) <= 10) {
    print(i)
    print(vars_in_table1[i])
    print(names(table1_dataset[vars_in_table1[i]]))
    cat_variables[cont] <- names(table1_dataset[vars_in_table1[i]])
    cont <- cont+1
  }
} 
cat_variables <- cat_variables[!is.na(cat_variables)]
table1_base <- print(CreateTableOne(vars = setdiff(vars_in_table1, stratifyby)
                                    , strata = stratifyby
                                    , factorVars = cat_variables
      ,data = table1_dataset, addOverall = T), varLabels = T)

```
# Ejecute esto en la consola para la salida html, el código a continuación usa kableExtra
```{r}
stratification_cats <- n_distinct(table1_dataset[,stratifyby])
```
# For console

```{r}
table1_base %>%
  kbl(caption = "Table 1 Emergency and sepsis. Stratified by ICU mortality", align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria") %>%
  add_header_above(c("","", "No", "Yes","",""))

#Exportar tabla
table1_base %>%
  kbl(caption = "Table 1 Emergency and sepsis. Stratified by ICU mortality", align = "c") %>%
  kable_classic_2(full_width = F, html_font = "Cambria") %>%
  add_header_above(c("","","No","Yes","","")) %>%
  save_kable("C:/Users/cjimenez10J/Documents/projects/r_urgencias_sepsis/r_urgencias_sepsis/Figures/table1_base.html", zoom = 10)


```

